/** Major and industrial cities per state — used for onboarding city selection only. */
export const INDIAN_STATE_CITIES: Record<string, readonly string[]> = {
  AN: ["Port Blair"],
  AP: [
    "Visakhapatnam",
    "Vijayawada",
    "Tirupati",
    "Kakinada",
    "Nellore",
    "Guntur",
    "Rajahmundry",
    "Anantapur",
    "Kadapa",
    "Vizianagaram",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
  ],
  AR: ["Itanagar", "Pasighat", "Tawang", "Naharlagun", "Roing"],
  AS: [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Tezpur",
    "Nagaon",
    "Tinsukia",
    "Bongaigaon",
    "Goalpara",
  ],
  BR: [
    "Patna",
    "Gaya",
    "Muzaffarpur",
    "Bhagalpur",
    "Darbhanga",
    "Purnia",
    "Bihar Sharif",
    "Begusarai",
    "Hajipur",
  ],
  CH: ["Chandigarh", "Mohali", "Panchkula"],
  CG: [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Rajnandgaon",
    "Raigarh",
    "Jagdalpur",
  ],
  DN: ["Silvassa", "Daman", "Diu"],
  DL: [
    "New Delhi",
    "Delhi",
    "Narela",
    "Okhla",
    "Mayapuri",
    "Naraina",
    "Bawana",
  ],
  GA: ["Panaji", "Margao", "Vasco da Gama", "Verna", "Mapusa", "Ponda"],
  GJ: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Ankleshwar",
    "Vapi",
    "Bharuch",
    "Morbi",
    "Junagadh",
    "Nadiad",
    "Kalol",
  ],
  HR: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Karnal",
    "Rohtak",
    "Hisar",
    "Sonipat",
    "Manesar",
    "Bawal",
    "Rewari",
    "Yamunanagar",
  ],
  HP: ["Shimla", "Baddi", "Solan", "Mandi", "Parwanoo", "Nalagarh", "Una"],
  JK: ["Jammu", "Srinagar", "Baramulla", "Anantnag", "Udhampur", "Kathua"],
  JH: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
  ],
  KA: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Dharwad",
    "Belagavi",
    "Ballari",
    "Tumakuru",
    "Shivamogga",
    "Hosapete",
    "Bidar",
    "Raichur",
    "Hassan",
    "Udupi",
  ],
  KL: [
    "Kochi",
    "Thiruvananthapuram",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Alappuzha",
    "Palakkad",
    "Kannur",
    "Kottayam",
    "Malappuram",
    "Ernakulam",
  ],
  LA: ["Leh", "Kargil"],
  LD: ["Kavaratti"],
  MP: [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Ratlam",
    "Pithampur",
    "Mandideep",
    "Satna",
    "Rewa",
  ],
  MH: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Thane",
    "Navi Mumbai",
    "Kolhapur",
    "Solapur",
    "Jalgaon",
    "Amravati",
    "Chandrapur",
    "Ahmednagar",
    "Satara",
    "Ratnagiri",
    "Raigad",
    "Palghar",
  ],
  MN: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
  ML: ["Shillong", "Tura", "Jowai", "Nongstoin"],
  MZ: ["Aizawl", "Lunglei", "Champhai", "Serchhip"],
  NL: ["Kohima", "Dimapur", "Mokokchung", "Tuensang"],
  OD: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Paradip",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Angul",
    "Jharsuguda",
    "Puri",
  ],
  PY: ["Puducherry", "Karaikal", "Yanam", "Mahe"],
  PB: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Mohali",
    "Patiala",
    "Bathinda",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Phagwara",
  ],
  RJ: [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Bhiwadi",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bhilwara",
    "Pali",
    "Sri Ganganagar",
  ],
  SK: ["Gangtok", "Rangpo", "Namchi", "Gyalshing"],
  TN: [
    "Chennai",
    "Coimbatore",
    "Hosur",
    "Tiruppur",
    "Salem",
    "Erode",
    "Tiruchirappalli",
    "Madurai",
    "Tirunelveli",
    "Thoothukudi",
    "Vellore",
    "Cuddalore",
    "Ranipet",
    "Sriperumbudur",
    "Ambattur",
    "Avadi",
    "Kanchipuram",
    "Thanjavur",
  ],
  TS: [
    "Hyderabad",
    "Warangal",
    "Karimnagar",
    "Nizamabad",
    "Khammam",
    "Ramagundam",
    "Secunderabad",
    "Sangareddy",
    "Patancheru",
    "Medak",
  ],
  TR: ["Agartala", "Udaipur", "Dharmanagar", "Ambassa"],
  UP: [
    "Lucknow",
    "Kanpur",
    "Noida",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Prayagraj",
    "Bareilly",
    "Aligarh",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Jhansi",
    "Mathura",
    "Firozabad",
    "Greater Noida",
  ],
  UK: [
    "Dehradun",
    "Haridwar",
    "Rudrapur",
    "Pantnagar",
    "Haldwani",
    "Kashipur",
    "Roorkee",
    "Sitarganj",
  ],
  WB: [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Siliguri",
    "Haldia",
    "Asansol",
    "Kharagpur",
    "Bardhaman",
    "Malda",
    "Raiganj",
    "Kalyani",
  ],
};

function normKey(value: string): string {
  return value.trim().toLowerCase();
}

export function getCitiesForStateCode(stateCode: string): string[] {
  const cities = INDIAN_STATE_CITIES[stateCode];
  if (!cities?.length) return [];
  return [...cities];
}

export function filterCitiesForState(stateCode: string, query: string): string[] {
  const cities = getCitiesForStateCode(stateCode);
  const q = normKey(query);
  if (!q) return cities;
  return cities.filter((city) => normKey(city).includes(q));
}

/** Case-insensitive exact match; returns canonical city label or null. */
export function resolveCityForState(
  stateCode: string,
  city: string,
): string | null {
  const trimmed = city.trim();
  if (!trimmed || !stateCode) return null;
  const key = normKey(trimmed);
  const match = getCitiesForStateCode(stateCode).find((c) => normKey(c) === key);
  return match ?? null;
}

export function isCityValidForState(stateCode: string, city: string): boolean {
  return resolveCityForState(stateCode, city) !== null;
}

export function getCityPlaceholderForState(stateCode: string): string {
  const cities = getCitiesForStateCode(stateCode);
  if (!cities.length) return "Search city…";
  return `Search e.g. ${cities.slice(0, 3).join(", ")}`;
}
